apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api-container
        image: larssonludvig/thenest:api
        imagePullPolicy: Always
        ports:
        - containerPort: 80
