apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: mysql-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
        name: mysql
    spec:
      nodeSelector: {}
      containers:
        - name: mysql
          image: ubuntu/mysql:edge
          imagePullPolicy: Always
          ports:
            - name: mysql
              containerPort: 3306
          volumeMounts:
            - name: mysql-config-volume
              mountPath: /etc/mysql/mysql.conf.d/mysql.cnf
              subPath: mysql.cnf
            - name: mysql-storage
              mountPath: /var/lib/mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "INSERT PASS HERE"
            - name: MYSQL_INITSB_SKIP_TZINFO
              value: "yes"
      volumes:
        - name: mysql-config-volume
          configMap:
            name: mysql-config
            items:
            - key: mysql.cnf
              path: mysql.cnf
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: hostpath-pvc
