apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hostpath-pvc
  namespace: database
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage: 20Gi