apiVersion: apps/v1
kind: Deployment
metadata:
  name: scraper
  namespace: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scraper
  template:
    metadata:
      labels:
        app: scraper
    spec:
      containers:
      - name: scraper-container
        image: larssonludvig/thenest:scraper
        imagePullPolicy: Always
        ports:
        - containerPort: 80
